version: "3.3"
services:
  webserver:
    image: nginx:latest
    restart: always
    ports:
      - 8181:80
    volumes:
      - /root/docker/webs:/usr/share/nginx/html
    depends_on:
      - database
    links:
      - database
  database:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=root@123
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 8088:80
